linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ineffassign
    - megacheck
    - misspell
    - staticcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - typecheck
    - unparam
    - unused
    - varcheck
    - varcheck
issues:
  exclude:
    # gosec:G404 causes false positive claim that we're using math.rand instead of crypto.rand even though we
    # clearly are not.
    - G404
    # gosec:G304 causes false positive "Potential file inclusion via variable". Would rather exclude this class
    # of issue than entirely disable gosec for such lines (I still want e.g. error checking).
    - G304
