version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - unparam
    - gocyclo
    - revive
    - gocritic
    - bodyclose
    - unconvert

  exclusions:
    rules:
      # Ignore G404 in test files - using math/rand for test data generation is acceptable
      - path: "_test\\.go"
        text: "Use of weak random number generator"
        linters:
          - gosec
      # Ignore G304 (file inclusion) - this is the core functionality of the tool
      - text: "G304"
        linters:
          - gosec
      # Ignore documentation complaints from revive
      - text: "package-comments: should have a package comment"
        linters:
          - revive
      - text: "exported: exported .* should have comment or be unexported"
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - goimports
