language: go
go:
  - "1.11"

install:
  - go get github.com/golang/lint/golint
  # errcheck's master does not support modules. Module support existed on master previously but was reverted because
  # it broke builds on Go versions below 1.10.4. While this is shaking out, install a version that does have module
  # support. See https://github.com/kisielk/errcheck/issues/150
  - (cd /tmp && git clone https://github.com/kisielk/errcheck && cd errcheck && git checkout 2f843a121b17b3902d9a6c965b5476dc618bb742 && go install && cd .. && rm -rf errcheck)

env:
  - GO111MODULE=on

script:
  - go build
  - go test ./...
  - go vet ./...
  - errcheck ./...
  - golint ./...
