language: go
go:
  - "1.11"

install:
  - go get github.com/golang/lint/golint
  # errcheck's master does not support modules. Module support existed on master previously but was reverted because
  # it broke builds on Go versions below 1.10.4. While this is shaking out, install a version that does have module
  # support. See https://github.com/kisielk/errcheck/issues/150
  - (cd /tmp && git clone https://github.com/kisielk/errcheck && cd errcheck && git checkout 2f843a121b17b3902d9a6c965b5476dc618bb742 && go install && cd .. && rm -rf errcheck)

env:
  # travis by default puts us in a GOPATH which causes module support to be turned off. force it on.
  - GO111MODULE=on

script:
  - go build
  - go test ./...
  - go vet ./...
  - errcheck ./...
  - golint ./...

  # End-to-end test of decryption.
  #
  # NOTE: passing passphrase to stdin is not a public interface; this behavior may change at any time.
  - echo -n test | ./saltybox passphrase-decrypt-file testdata/hello.txt.salty /tmp/hello-decrypted.txt
  - diff testdata/hello.txt /tmp/hello-decrypted.txt

  # End-to-end test of encryption. While compatible evolution of saltybox is possible, this helps detect
  # any *accidental* change in output.
  #
  # NOTE: passing passphrase to stdin is not a public interface; this behavior may change at any time.
  - echo -n test | ./saltybox passphrase-encrypt-file testdata/hello.txt /tmp/hello-encrypted.txt.salty
  - diff testdata/hello.txt.salty /tmp/hello-encrypted.txt.salty
