language: go
go:
  - "1.11"

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.10.2
  - ./bin/golangci-lint --version

env:
  # travis by default puts us in a GOPATH which causes module support to be turned off. force it on.
  - GO111MODULE=on

script:
  - ./bin/golangci-lint run --max-issues-per-linter 500 --max-same-issue 500
  - go build
  - go test ./...

  # End-to-end test of decryption. The immutable committed encrypted data must never fail to decrypt.
  #
  # NOTE: passing passphrase to stdin is not a public interface; this behavior may change at any time.
  - echo -n test | ./saltybox passphrase-decrypt-file testdata/hello.txt.salty /tmp/hello-decrypted1.txt
  - diff testdata/hello.txt /tmp/hello-decrypted1.txt

  # End-to-end test of encryption followed by decryption.
  #
  # NOTE: passing passphrase to stdin is not a public interface; this behavior may change at any time.
  - echo -n test | ./saltybox passphrase-encrypt-file testdata/hello.txt /tmp/hello-encrypted2.txt.salty
  - echo -n test | ./saltybox passphrase-decrypt-file /tmp/hello-encrypted2.txt.salty /tmp/hello-decrypted2.txt
  - diff testdata/hello.txt /tmp/hello-decrypted2.txt
