//! Golden test vector validation for the saltybox2 format.
//!
//! The vectors in testdata/golden-vectors-v2.json are generated by
//! testdata/generate-golden-vectors-v2.py using an independent
//! implementation stack (Argon2 via argon2-cffi, XChaCha20-Poly1305 via
//! libsodium/PyNaCl). Agreement here is evidence the Rust implementation
//! matches the specified format — including the AAD construction over magic
//! and header — rather than merely agreeing with itself.
//!
//! The vectors deliberately use cheap Argon2 parameters: saltybox2 records
//! the parameters in each file's header, so a vector built with a tiny work
//! area is exactly as valid as one built at the expensive write defaults.
//! Every vector therefore runs fast, and unlike the v1 golden tests there
//! is no need for an ignored-by-default subset split.

use base64::{Engine, engine::general_purpose::STANDARD as BASE64_STANDARD};
use saltybox::format::FormatEngine;
use saltybox::format_v2::{V2Engine, encrypt_deterministic};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct GoldenVectorV2 {
    comment: String,
    passphrase: String,
    plaintext: String,
    salt: String,
    nonce: String,
    m_cost_kib: u32,
    t_cost: u32,
    p_cost: u32,
    armored: String,
}

#[test]
fn test_all_v2_golden_vectors() {
    let vectors: Vec<GoldenVectorV2> =
        serde_json::from_str(include_str!("../testdata/golden-vectors-v2.json"))
            .expect("failed to load v2 golden vectors");
    assert!(!vectors.is_empty(), "no v2 golden vectors found");

    for (i, vector) in vectors.iter().enumerate() {
        let context = format!("vector {} ({})", i, vector.comment);

        let passphrase = BASE64_STANDARD
            .decode(&vector.passphrase)
            .unwrap_or_else(|e| panic!("{context}: failed to decode passphrase: {e}"));
        let plaintext = BASE64_STANDARD
            .decode(&vector.plaintext)
            .unwrap_or_else(|e| panic!("{context}: failed to decode plaintext: {e}"));
        let salt: [u8; 16] = BASE64_STANDARD
            .decode(&vector.salt)
            .unwrap_or_else(|e| panic!("{context}: failed to decode salt: {e}"))
            .try_into()
            .unwrap_or_else(|_| panic!("{context}: salt must be 16 bytes"));
        let nonce: [u8; 24] = BASE64_STANDARD
            .decode(&vector.nonce)
            .unwrap_or_else(|e| panic!("{context}: failed to decode nonce: {e}"))
            .try_into()
            .unwrap_or_else(|_| panic!("{context}: nonce must be 24 bytes"));

        // Deterministic encryption must reproduce the independently
        // generated armored output exactly.
        let armored = encrypt_deterministic(
            &passphrase,
            &plaintext,
            &salt,
            &nonce,
            vector.m_cost_kib,
            vector.t_cost,
            vector.p_cost,
        )
        .unwrap_or_else(|e| panic!("{context}: encryption failed: {e}"));
        assert_eq!(armored, vector.armored, "{context}: armored mismatch");

        // And the engine must decrypt the independent implementation's
        // output back to the original plaintext.
        let payload = V2Engine
            .unarmor(&vector.armored)
            .unwrap_or_else(|e| panic!("{context}: unarmor failed: {e}"));
        let decrypted = V2Engine
            .decrypt(&passphrase, &payload)
            .unwrap_or_else(|e| panic!("{context}: decryption failed: {e}"));
        assert_eq!(*decrypted, plaintext, "{context}: plaintext mismatch");
    }
}
